---
- name: "openssh | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "openssh | Include authorized keys command tasks"
  ansible.builtin.include_tasks:
    file: "deploy_openssh_authorized_keys_command.yml"
  when:
    - "vars['openssh_settings_authorized_keys_command_content'] is defined"
    - "vars['openssh_settings_authorized_keys_command_content'] != ''"
- name: "openssh | Include deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy_openssh.yml"
  when:
    - "vars['openssh_settings'] is defined"
    - "vars['openssh_settings'] != []"
